Improvement/check block sequencing
blockworks-foundation/lite-rpc pull request #299
Opened 2024-01-22 11:51 UTC by grooviegermanikus

2024-01-22 12:01 UTC, godmodegalactus submitted a review, later dismissed

2024-01-30 14:57 UTC, godmodegalactus commented
Fix conflicts and clippy

2024-02-07 13:01 UTC, godmodegalactus requested changes

2024-02-07 13:01 UTC, godmodegalactus commented on lite-rpc/src/main.rs
> +    debugtask_blockstream_slot_progression(
Should be optional.

2024-02-07 13:04 UTC, godmodegalactus submitted a review, later dismissed

2024-02-07 13:24 UTC, grooviegermanikus commented
hide grpc_inspect behind flag

2024-02-07 14:33 UTC, godmodegalactus approved these changes

2024-02-07 14:51 UTC, merged