postgres and prometheus
blockworks-foundation/lite-rpc pull request #41
Opened 2023-01-29 10:52 UTC by aniketfuryrocks

- WIP: postgres ssl
- postgres openssl types fixed but can't make certs to work
- connect to postgres
- ignore env, pks and pem files
- WIP:
- successfully write to postgres
- have slot
- rebase unbounded
- write to postgres after every tx_batch
- working and logging
- postgres connection revival
- prometheus
- fixed comments left by pan in #40

2023-01-29 11:06 UTC, aniketfuryrocks commented
env variables needed to implemented

2023-01-30 10:14 UTC, godmodegalactus requested changes

2023-01-30 10:14 UTC, godmodegalactus commented on src/workers/tx_sender.rs
> +                            signature: sig.clone(),
This should not be done here, but in block subscription stage where we iterate through all the transactions to find if they are in the block or not.

2023-01-31 11:12 UTC, godmodegalactus approved these changes

2023-01-31 11:13 UTC, merged